#!/usr/bin/env bash
#Write a Bash script that displays the content of the file /etc/passwd.

filename="etc/passwd"
while read -r line
do
	set "$line"
	echo "$1"
	echo "$3"
	echo "$6"
done < "$filename"
