#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
((i = 1))

while ((i <= 10));
do
	if ((i != 8));then
		if ((i != 4));then
			echo "Best School"
		else
			echo "bad luck"
		fi
	elif ((i == 8));then
		echo "good luck"
	fi
	((i++))
done
